import localFont from 'next/font/local'
import type { Metadata } from "next";
import "./globals.css";

const dmSansRegular = localFont({
  src: "./fonts/DM_Sans/DMSans-VariableFont_opsz,wght.ttf",
  variable: "--font-dm-sans-regular"
})

const dmSansItalic = localFont({
  src: "./fonts/DM_Sans/DMSans-Italic-VariableFont_opsz,wght.ttf",
  variable: "--font-dm-sans-italic"
})

const bricolageGrotesque = localFont({
  src: "./fonts/Bricolage_Grotesque/Bricolage_Grotesque/BricolageGrotesque-VariableFont_opsz,wdth,wght.ttf",
  variable: "--font-bricolage-grotesque"
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSansItalic.variable} ${dmSansRegular.variable} ${bricolageGrotesque.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
